name: pytorch_utils

channels:
  - pytorch
  - conda-forge

dependencies:
  - dill
  - pytest
  - hypothesis
  - pytorch
  - torchvision
  - matplotlib
  - tqdm
  - pyyaml
  - scikit-learn
  - deprecated
  - pydantic

  # developer
  - bump2version
