name: pytorch_utils

channels:
  - pytorch
  - conda-forge

dependencies:
  - python >=3.8,<3.10
  - pytorch >=1.7.1
  - torchvision
  - matplotlib
  - py-opencv
  - pydantic
  - pandas
  - tqdm
  - pyyaml
  - scikit-learn
  - dill
  - deprecated

  # test
  - pytest
  - hypothesis

  # developer
  - bump2version
