name: Deploy pytorch_utils

on:
  push:
  pull_request:
  release:
    types: [edited, published]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      FILENAMES: temp-filenames.txt
      ANACONDA_LABEL: dev  # default is dev "release" on commit

    steps:
    - uses: actions/checkout@v2

    - name: Install conda build libraries
      run: |
        $CONDA/bin/conda install conda-build anaconda-client

    # build, then also store the file paths that were built
    - name: Build pytorch_utils
      run: |
        cd ./conda
        $CONDA/bin/conda-build -c pytorch -c conda-forge .
        $CONDA/bin/conda-build -c pytorch -c conda-forge . --output > $FILENAMES

    - name: Change anaconda label on release
      if: github.event.release
      run: |
        echo "ANACONDA_LABEL=main" >> $GITHUB_ENV

    - name: Change anaconda label on prerelease
      if: github.event.release.prerelease
      run: |
        echo "ANACONDA_LABEL=rc" >> $GITHUB_ENV

    - name: Upload to Anaconda Cloud
      if: ${{ github.event.release || github.ref == 'refs/heads/master' }}
      env:
        ANACONDA_TOKEN: ${{ secrets.HAYDNSPASS_ANACONDA_TOKEN }}
      run: |
        set -x
        cd ./conda
        while read PATH; do
          $CONDA/bin/anaconda -t $ANACONDA_TOKEN upload --force -l ${{ env.ANACONDA_LABEL }} -u haydnspass $PATH
        done < $FILENAMES
